### ISSUE TITLE
Versioning -- YYYY.SEMESTER.FIXES

### ISSUE THREAD

**Issue by zerothi** [dtudk/dtumathtools#10]
Going forward it might be ideal to move to a more stringent development order.

This package will be at the core of new students and will govern the course environments in the years to come.

To ensure that the versioning corresponds ideally with courses at DTU the following is proposed (discussed with Tue and Jakob).
(all comments are welcome, we need to ensure the best experience and flexible development cycle of this package)

- the project should be split into several branches
  - `develop` for the *next* semester
  - `YYYY.SEMESTER` for each years package dependencies YYYY and each SEMESTER dependencies
  - Every `YYYY.SEMESTER` branch can get bug fixes during the semester, but should not be touched after semester
  - On this branch one should create releases for each of the bug fixes that is encountered. So the first release would
    always be `YYYY.SEMESTER.0`. It just gives the flexibility of fixing stuff on the fly.
 
The above would be the development cycle of the branches and thus each semester a new branch would be created.
*(this could even be done in a workflow branching off the `develop` branch -- use with care ;) )*  

This brings us to the versioning:

Ideally one should be able to do:
```
pip install "dtumathtools==2023.1.*"
```
to get the dependencies for the 1st semester of 2023.
This would allow that documentations for each course can specifically note *which* year and semester they belong to. When going forward we can easily imagine that the requirements will be updated on a semester basis (consider bug-fixes or something else).
Since students will generally only have access to the course material for the year they participated, it is vital that they can get the same environment again (consider 3 years later, the dependencies have moved a lot, and nothing works).

Lastly, let me add a new complexity that *may* enter.

Consider that a course would later add to this years dependency a package called `mydep`.
We could imagine that this project has `extras` defined to accommodate different courses.

I could for instance have a course `01234` which wants to add `mydep`

We would then have this in `pyproject.toml`:
```toml
01234 = [
    "mydep==0.1.1"
]
```
or similar.
In this way students could exactly define their course at install time:
```
pip install dtumathtools[01234]==2023.1
```
and get the extra dependencies. This is just a suggestion, but could go a long way to cover lots of courses that want to rely on dtumathtools without complicating matters for their students.

**Comment by Chrillebon** [comment]
The versioning is a great idea! The specific naming, YYYY.SEMESTER, could work. However, I have the following thoughts:

- Currently very few to no commands target the fall semester, and so changes are likely to be focussed on the spring semester.
- If the above holds, maybe we only need "YYYY.fixes" (offset from school year)?
- The naming with year and semester would imply that during the spring semester, students have to download the "previous years version". Maybe the naming should then be "2324", "2425", ...?
- Supporting your naming is that during the summer vacation, people might actually have (enough) time to do major changes and updates to this package.
- Does this force updating to a new version every year? Might not be a problem for students, but from the development side, it forces changes every year? Might also be alright, since we need to ensure that it still supports new/coming versions of python.

In terms of `extras`, this is already defined and part of the package. However, it is defined in the `setup.py` file (under `extras_require`) and not in a `pyproject.toml`. If it makes a difference to anyone I would not mind switching to that setup structure, but we do not need to do that to get `extras` to work.

**Comment by zerothi** [comment]
> The versioning is a great idea! The specific naming, YYYY.SEMESTER, could work. However, I have the following thoughts:
> 
>     * Currently very few to no commands target the fall semester, and so changes are likely to be focussed on the spring semester.

Some courses may run in both fall and spring, and later, new courses may only run in one of the semesters. I think it is best to foresee that we should have both semesters.
Then we are on the safe side ;)

> 
>     * If the above holds, maybe we only need "YYYY.fixes" (offset from school year)?

See above.

> 
>     * The naming with year and semester would imply that during the spring semester, students have to download the "previous years version". Maybe the naming should then be "2324", "2425", ...?

Hmm, I think the above `YYYY.SEMESTER` would fix that, no?

I.e. the version should always refer to the course start dates, that might be a bit confusing, but for courses that only run autumn 23, then installing 2324 might also be confusing.  
I th
> 
>     * Supporting your naming is that during the summer vacation, people might actually have (enough) time to do major changes and updates to this package.
> 
>     * Does this force updating to a new version every year? Might not be a problem for students, but from the development side, it forces changes every year? Might also be alright, since we need to ensure that it still supports new/coming versions of python.
> 
> 
> In terms of `extras`, this is already defined and part of the package. However, it is defined in the `setup.py` file (under `extras_require`) and not in a `pyproject.toml`. If it makes a difference to anyone I would not mind switching to that setup structure, but we do not need to do that to get `extras` to work.

**Comment by Chrillebon** [comment]
That makes sense! So the version will be `2023.2.<>` for the coming semester, and `2024.1.<>` coming up for the spring semester. 

I will leave this issue open till both the versioning and the move to `pyproject.toml` is complete.

**Comment by zerothi** [comment]
Yes, but I think we'll leave it until in November. :)

**Comment by so-rose** [comment]
Just chiming in; why not Semantic Versioning `MAJOR.minor.patch` (aka. `M.m.p`)? <https://semver.org/>?

# What's That?
SemVer **guarantees** that code relying on `M` will work on all future `M`. In other words, *backwards compatibility is guaranteed within a major version.*

This is a feature that can have immense reliability => ecosystem benefits. Anyone using this library, can get bug fixes and new features (without na aggressive deep freeze), while being *guaranteed* that their code will never spontaneously break. Guides, examples, little scripts, etc. never breaking on the same major version is the kind of reliable that I'd expect a course reusing code across years would be very thankful for.

## Isn't That Horrifically Not Agile??
It may feel limiting to development to have to bump the major version to break any backwards compatibility. It may also feel fluffy to draw the line between bugs and use cases - if a bug is relied on by someone, does fixing it imply a major version bump?

I would suggest, however, that these are _inherent complexities_ to altering widely used software. These questions must be dealt with sooner or later, and it's always political. Here, SemVer makes it:
- _Difficult to ignore_. "My code broke with the non-major update" now implies broken trust, not just unfortunateness, and that's far more difficult to ignore.
- _Consistently apolitical_. The issue with softer methods, ex. deprecation, is that users generally don't care! Code that **works**, and has for _years_, tends to just sit, until it can't. Will a course really want to change one of a hundred working scripts, when a billion other things have higher priority, just because of a harmless deprecation notice? "We warned you" won't fix the perceived-spontaneous extra work hours required when 20 students can't plot like they could last year. Especially if that is a per-semester thing.

Such limitations are thus, perhaps, **well placed** considering the complexity of the problem space - much as strict C++ style guides!

## Won't that Make YEAR Versions Impossible?
SemVer works great with YEAR as major version, *if in fact yearly breaks in backwards compatibility are desired*.

I'm going to presume that it might be a bit aggressive to break the entire Polytechnical Foundation once per year (I'd argue, this is one example of how SemVer makes it easier to ask the right kinds of questions about these kinds of problems). HOWEVER, there's nothing wrong with skipping years in SemVer. "2023 Edition" could, when enough breaking changes accumulate in the "next" branch, be supplanted by a ex. "2025 Edition", with one year of bug fixes extra for "2023 Edition" while courses are told to migrate.

Do they never migrate? Maybe "2025 Edition" was premature. Or maybe "2023 Edition" just needs a longer support window.

# Development Practice
There are lots of great workflows once one commits to semver. Generally, protecting main and keeping breaking changes in a "next" branch is a good idea. If you trust your testing solution, "release branches" (ex. "2023" branch) can be nice. Otherwise, keeping main usually incrementing minor/patch versions with direct PRs and rebasing in "next" when a major version drops is a very clean solution.

If one likes Conventional Commits, one can even automate releases w/changelogs generated from commit logs.

**Comment by zerothi** [comment]
I concur that semver versioning is useful in steady developments.

However, this package is year specific, and hence going beyond the semver is required.
The point is that there *might* be something that changes over the summer break and then we need to signal this clearly to students/employees. Using the `m` here seems like the easiest and simplest approach.

Say if a course discovers a major bug in a reliant library and needs to step to the next major. They would have to bump the year (since it breaks backwards compatibility). This is not ideal.

So I think semver isn't really fitting here. Since there might be something that a course really needs that breaks something. 

What we are going to use in semver, is that:
`YYYY.<semester>` is a progression of student semesters. The micro release then follows the semver terminology.

**Comment by zerothi** [comment]
This suggestion has been adopted, see the `DEPLOY.md` for details.
