### ISSUE TITLE
Version requirements

### ISSUE THREAD

**Issue by zerothi** [dtudk/dtumathtools#15]
Currently there are two exclusive requirements:

```
sympy-plot-backends~=2.4
sympy~=1.12
```
however this translates to:
```
sympy-plot-backends~=2.4.0
sympy~=1.12.0
```
is this intentional, or an omission?

**Comment by Chrillebon** [comment]
The two are different, and the notation is intentional. As described [here](https://peps.python.org/pep-0440/#compatible-release), the requirements ensure that spb satisfy `>=2.4` and `==2.*` (and in the same way for sympy). This way, updates and new functionality would be added as they came, but keep out major and breaking changes (`>=3.0`). 

Are you suggesting changing to the other notation to only keep bugfixes, and not smaller version changes?

**Comment by zerothi** [comment]
Sorry, you are right, I had forgotten it was the compatible check, not the NOT op. So no problem!
