### ISSUE TITLE
[Suggestion] `from *` in README

### ISSUE THREAD

**Issue by so-rose** [dtudk/dtumathtools#18]
The suggestion stems directly from a strong [PEP8](https://peps.python.org/pep-0008/) requirement:

```
Wildcard imports (from <module> import *) should be avoided,
as they make it unclear which names are present in the namespace,
confusing both readers and many automated tools.

There is one defensible use case for a wildcard import,
which is to republish an internal interface as part of a public API (for example,
overwriting a pure Python implementation of an interface with the definitions from
an optional accelerator module and exactly which definitions will be overwritten
isn’t known in advance).
```

In short, using `from *` is a habit that can very quickly lead to very strange bugs.
I would strongly suggest not encouraging this anywhere, let alone in a beginner oriented tool.

In practice, this would involve replacing `from dtumathtools import *` with
```python
from dtumathtools import dtuplot
from dtumathtools import dtutools
```

More explicit, but less magic.

**Comment by Chrillebon** [comment]
We can fix it in the `README`, but I assume that you are referring to the general use of programming within the course and that this issue is directed at that.

I agree, that this is the correct programming (and python) practice, and even should be avoided in a beginner-oriented tool. However, this is not meant to be a programming tool-kit. This is a mathematics tool-kit utilizing functionality inside `sympy`. The choice to do so in the `README` is to align with how it is being done in the demos (import of both `dtumathtools `and `sympy`).

We can then have a discussion of whether `*` imports should be done at all in the introductory programming course (currently, this is how the two used packages in the course are being imported). Much of the reasoning has to do with the target audience being mostly people who have never seen programming before and simply want to use it as a tool to get mathematics to work. Here are my arguments for choosing the `*` notation:

- This makes a very simple import for all scripts used during the course. This import will be the same across all demos, scripts, exercises, etc. This ensures that simply copying these lines of code gives the users all the functionality that they need, and be able to copy lines from all other scripts and expect them to work.
- The complete set of imports required throughout the course is very limited (only `sympy `and during the spring also sometimes `dtumathtools`). Especially in the first few months most, if not all, functionality will be entirely within the `sympy `package. This shortens the notation and writing when setting up formulas and writing matrices and equations, as `sympy` (or `sp`) would have to be written in front of _every single command_.
- Importing `sympy` using the star will make for simpler and more intuitive code to get up and running without worrying about if it is part of a package or not, especially when most people have little to no experience with python, let alone packages. `dtumathtools` is then simply mirroring this import.
- The introductory mathematics course is not a programming course and is thus not responsible for teaching correct programming practices. I know that is an extreme argument, as I mostly agree with what you are saying. Also learning correct programming practices would be an amazing benefit. However, with the above arguments, I see the scale tip slightly to the `*` imports favor.

Would love to hear your take on these points of view.

**Comment by so-rose** [comment]
@Chrillebon Thanks for your response! I'll explain in depth.

Let me preface this with the following: Simple solutions to namespace problems _don't exist_. At its core, this is the absolute danger of `from *`: Easy complexity masquerading as elegance.



# "Lies to Children": Beginners Don't Need To Know Everything
> This makes a very simple import for all scripts used during the course.

Shielding beginners from non-critical complexities is very important, and I completely respect the terribly difficult balancing act involved. This is the term "lies to children" (minted in the context of elementary school math education). I recognize this.

With that in mind, let me bring attention to the really, really, **really** critical piece of this PEP8 requirement:

> ...they [`from*`] make it unclear which names are present in the namespace...

Nothing is more valuable to a beginner than **understanding**. Any morsel of understanding is rare at this stage; it's like feeling a rock on a climbing wall at night.

With that in mind, `from *` **robs beginners of the ability to understand where names come from**, at the _precise_ moment where they're trying to figure out where on earth `sympy` comes from. Which, incidentally, unknown to them, happens to be touching against a _truly difficult namespace problem_.

# "Just Works" < "Reliably Works"
> This ensures that simply copying these lines of code gives the users all the functionality that they need, and be able to copy lines from all other scripts and expect them to work.

As I understand it, students aren't just running code. Every student will be writing and handing in code, and will be graded on what they hand in. No matter how it's sliced, student will have to  _reason about their own code_. How can they do that, if it is made impossible to understand where the functionality that code relies on comes from?

There are few Python script in the world from which lines can be copied from such that they "just work". Simply invoking `random()` requires `from random import random`, and I cannot imagine a world where `from dtumathtools import dtutools` is unacceptable while `from random import random` is.

Clearly, it's not about copy/paste "always working". It's about all scripts **remaining within a beginner's ability to reason about**. With that, comes the crux of my argument: **I cannot reason about code relying on things I don't know what are**. This is an identity statement no matter my skill level.

Take this example:
```python
from dtumathtools import *

print(sympy.sqrt(3))
```

If I've never seen code before, I'm asking myself things like:
- What does `*` mean?
- What does `sympy` mean, where did it come from?
- Why does `sympy` stop working unless `from dtumathtools import *` is there? I heard `sympy` was an external thing, but did I mishear? Is it actually a DTU thing?

There's no reason for a beginner to be spending their executive budget on these things, when something as obvious as
```python
from dtumathtools import sympy

print(sympy.sqrt(3))
```
is _right there_.

# Namespace Issues Breed Expensive (in kr) Chaos
_Inevitably, the Namespace Kraken visits us all._

Some ways `from *` makes it worse:
- Students will google `sympy` stuff, I promise. `import sympy` will be plastered at the top of every SO answer. Incidentally, because `from *` floods the namespace, simply using `import sympy` **might break `from dtumathtools import *`**. Because nobody knows to `from dtumathtools import sympy`, students will quickly end up with slightly different versions of sympy.
- A version of sympy incompatible with `dtumathtool`'s might end up installed into the system environment, because a student hasn't grasped that `sympy` is coming from the `*`. This happens the moment `dtumathtools` ex. locks an older `sympy` to meet its own promises, as the yearly release cycle promises (#10). Now the real strangeness can begin. Featuring, now, a dependency problem (incidentally, another nasty namespace problem).

One could say things like "don't search up third party answers, stick to our examples". Say 20% of the ~2000 students don't listen (a generously low fraction), and say 25% of them encounter an issue like this, which could have been mitigated with an 80% success rate using explicit imports. I'll stop short of estimating TA hours (and kr spent), but more importantly, **wasn't the point to encourage computational thinking**?

At the very least, I can nearly guarantee you that a sizeable amount of students will become convinced either that:
- `sympy` is something that you can always use in Python.
- `sympy` is some DTU thing that clearly can't work without `dtumathtools`.

Which, of course, is a far bigger problem than getting into the bad habit of `from *`.

# Hiding Complexity Doesn't Remove It
> The complete set of imports required throughout the course is very limited

No, it's not. The imports are still there, except now, they are ghosts - can't be reasoned about. Especially by beginners, who don't know to look for `__all__` in an `__init__.py`.

"But do beginners really need to know about every import?" YES! **Don't use tools you don't understand** is a principle throughout engineering for a reason. We enshrine it by saying things like "don't use StackOverflow code you don't understand".
- Need to plot? `from dtumathtools import dtuplot`.
- Need the course-compatible version of `sympy`? `from dtumathtools import sympy`.

> Especially in the first few months most, if not all, functionality will be entirely within the sympy package.

I severely doubt that.
- Decimal Math? `import decimal`
- Random number? `import random`
- Load a CSV? `import csv`.
- Timing Code? `import time`.

I'm not suggesting, "don't use any imported things". I'm suggesting, "force students to be explicit about which tools they reach for", down to individual names.

## `from` Can Be a Good Idea
> This shortens the notation and writing when setting up formulas and writing matrices and equations, as sympy (or sp) would have to be written in front of every single command.

`from` is not evil, only `from *` (yes, evil!). There's nothing wrong (well, it depends, but _that's_ an advanced concern) with `from` in general:
```python
from sympy import sqrt

print(sqrt(5))
```

Why? Because **now I, a beginner, understand exactly where `sqrt` is coming from**. It's explicit and readable. `import this` would be proud.

> Explicit is better than implicit.

> Readability counts.


# In Conclusion
> Importing sympy using the star will make for simpler and more intuitive code to get up and running without worrying about if it is part of a package or not...

> The introductory mathematics course is not a programming course and is thus not responsible for teaching correct programming practices.

`from *` isn't simpler in practice, doesn't save LOC, it doesn't enable "just works" copy/pasting, and it's an active barrier to understanding something that **actually enables all of that**: _Where names come from._

_A course that relies on programming is a programming course._ Sorry. Just like any website with a login page is a security instructor. On a similar note, what's wrong about encouraging students to hand in code that avoids the most egregious of blunders? The kind of blunders that suck up hours and hours of student _and TA_ frustration? `from *` isn't a stylistic choice like `'` vs `"` to `cs101`; avoiding it is borderline self-care.

If there is still doubt, consider this concluding reference to PEP8.

> There is one defensible use case for a wildcard import, which is to republish an internal interface as part of a public API...

Such guides generally do not speak so strongly. There are very hard-learned lessons across billion dollar industries behind why.

**Comment by zerothi** [comment]
I'll close this, we can always open this again.
